# Generated by Django 5.1.4 on 2026-01-23 14:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditSummary',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_summary', serialize=False, to='customer.customer')),
                ('credit_invoices_total', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Sum of all credit invoices (after discount/advance)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_purchased_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of all purchased payments', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('returns_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of all approved returns', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Total credit = invoices + purchased - returns', max_digits=12)),
                ('debit_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Total payments made by customer', max_digits=12)),
                ('balance_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Outstanding balance = credit - debit (negative = customer has credit)', max_digits=12)),
                ('total_invoices_count', models.PositiveIntegerField(default=0, help_text='Number of credit invoices')),
                ('unpaid_invoices_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Number of unpaid/partially paid invoices')),
                ('last_invoice_date', models.DateTimeField(blank=True, db_index=True, help_text='Date of first unpaid credit invoice (if balance > 500)', null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of most recent payment', null=True)),
                ('is_overdue', models.BooleanField(db_index=True, default=False, help_text='True if last_invoice_date > 6 months old')),
                ('has_outstanding_balance', models.BooleanField(db_index=True, default=False, help_text='True if balance_amount > 0')),
                ('last_calculated', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this summary was recalculated')),
                ('calculation_version', models.PositiveIntegerField(default=1, help_text='Incremented each time calculation logic changes')),
            ],
            options={
                'verbose_name': 'Customer Credit Summary',
                'verbose_name_plural': 'Customer Credit Summaries',
                'db_table': 'customer_credit_summary',
                'indexes': [models.Index(fields=['has_outstanding_balance', '-balance_amount'], name='idx_outstanding_bal'), models.Index(fields=['is_overdue', '-last_invoice_date'], name='idx_overdue'), models.Index(fields=['-credit_amount'], name='idx_credit_desc'), models.Index(fields=['-balance_amount'], name='idx_balance_desc'), models.Index(fields=['-last_calculated'], name='idx_last_calc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit_invoices_total__gte', 0)), name='credit_invoices_non_negative'), models.CheckConstraint(condition=models.Q(('credit_purchased_total__gte', 0)), name='purchased_non_negative'), models.CheckConstraint(condition=models.Q(('returns_total__gte', 0)), name='returns_non_negative'), models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0)), name='debit_non_negative')],
            },
        ),
    ]
