# Generated by Django 5.1.4 on 2026-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_payment_created_by_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'View Dashboard'), ('export_customers', 'Export Customers')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customercreditsummary',
            options={'permissions': [('export_summery', 'Customer Summery Details')], 'verbose_name': 'Customer Credit Summary', 'verbose_name_plural': 'Customer Credit Summaries'},
        ),
    ]
