# Generated by Django 5.1.4 on 2026-03-18 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_referred_by_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_type', 'is_deleted'], name='customer_pa_custome_867496_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='customer_pa_payment_a6c7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date', 'id'], name='customer_pa_custome_81b4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_deleted', 'payment_type'], name='customer_pa_is_dele_a93d1d_idx'),
        ),
    ]
