# Generated by Django 5.2 on 2026-06-25 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_customer_referred_by_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_deleted'], name='customer_cu_is_dele_531b71_idx'),
        ),
    ]
