# Generated by Django 5.2 on 2026-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_customer_cu_is_dele_531b71_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], default='CASH', help_text='Payment method used', max_length=20),
        ),
    ]
