# Generated by Django 5.1.4 on 2026-01-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(help_text='Cloudflare R2 URL of the generated PDF', max_length=500)),
                ('filename', models.CharField(help_text='PDF filename in storage', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the PDF was generated')),
                ('last_invoice_updated_at', models.DateTimeField(help_text='Invoice updated_at timestamp when PDF was generated')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='PDF file size in bytes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PDF is the current active version')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who triggered PDF generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice PDF',
                'verbose_name_plural': 'Invoice PDFs',
                'db_table': 'invoice_pdf',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['invoice', 'is_active'], name='invoice_pdf_invoice_3575e4_idx'), models.Index(fields=['generated_at'], name='invoice_pdf_generat_4647c6_idx'), models.Index(fields=['last_invoice_updated_at'], name='invoice_pdf_last_in_0bf4b3_idx')],
            },
        ),
    ]
