# Generated by Django 5.1.4 on 2026-01-12 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatementPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(help_text='Statement start date')),
                ('to_date', models.DateField(help_text='Statement end date')),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text="Customer's balance at to_date when PDF was generated", max_digits=12)),
                ('pdf_url', models.URLField(help_text='Cloudflare R2 URL of the generated PDF', max_length=500)),
                ('filename', models.CharField(help_text='PDF filename in storage', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the PDF was generated')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='PDF file size in bytes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this PDF is the current active version')),
                ('customer', models.ForeignKey(help_text='Associated customer', on_delete=django.db.models.deletion.CASCADE, related_name='statement_pdfs', to='customer.customer')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who triggered PDF generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statement_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement PDF',
                'verbose_name_plural': 'Statement PDFs',
                'db_table': 'statement_pdf',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['customer', 'from_date', 'to_date', 'is_active'], name='statement_p_custome_d574ee_idx'), models.Index(fields=['customer', 'closing_balance'], name='statement_p_custome_7b5698_idx'), models.Index(fields=['generated_at'], name='statement_p_generat_fd8cf8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'from_date', 'to_date'), name='unique_active_statement_per_date_range')],
            },
        ),
    ]
