# Generated by Django 5.1.4 on 2025-11-20 12:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Optional: Hex color code, e.g., #FF0000', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTHsnCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))])),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))])),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the UOM, e.g., Piece, Dozen, Meter', max_length=50)),
                ('short_code', models.CharField(help_text='Abbreviation for the UOM, e.g., pcs, doz, m', max_length=10, unique=True)),
                ('category', models.CharField(help_text='Type of UOM, e.g., Quantity, Weight, Length, Volume', max_length=50)),
                ('base_unit', models.BooleanField(default=False, help_text='Marks if this is the base unit for conversions')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Factor to convert to base unit (e.g., 1 dozen = 12 pcs)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this UOM', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this UOM is active or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(help_text='The brand of the product', max_length=255)),
                ('name', models.CharField(help_text='The name of the product', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the product', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('cloth_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.clothtype')),
                ('hsn_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.gsthsncode')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.uom')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The product image file.', upload_to='product_images/')),
                ('image_url', models.URLField(blank=True, help_text='The URL of the product image.', max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image for accessibility.', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Is this the main image for the product?')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='inventory.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
            options={
                'ordering': ['-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Purchase price must be greater than 0')])),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Selling price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Selling price must be greater than 0')])),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Quantity cannot be negative')])),
                ('damaged_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The quantity of the product that is damaged', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Damaged quantity cannot be negative')])),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum stock level before reorder alert', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Minimum quantity cannot be negative')])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Discount cannot be negative'), django.core.validators.MaxValueValidator(100, 'Discount cannot exceed 100%')])),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Commission cannot be negative'), django.core.validators.MaxValueValidator(100, 'Commission cannot exceed 100%')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='inventory.color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='inventory.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='inventory.size')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('RETURN', 'Customer Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Mark as Damaged'), ('INITIAL', 'Initial Stock')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Selling price at time of transaction', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit for sale transactions', max_digits=12, null=True)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='For SALE transactions: quantity allocated from source_inventory_log', max_digits=12, null=True)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='For STOCK_IN/INITIAL: remaining quantity available for allocation', max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total value of the transaction', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('source_inventory_log', models.ForeignKey(blank=True, help_text='For SALE transactions: points to the STOCK_IN/INITIAL log this sale is allocated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_sales', to='inventory.inventorylog')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='supplier.supplierinvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['variant', 'timestamp'], name='inventory_i_variant_1320cc_idx'), models.Index(fields=['transaction_type', 'timestamp'], name='inventory_i_transac_14c4f1_idx'), models.Index(fields=['created_by', 'timestamp'], name='inventory_i_created_e7a15d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['status'], name='inventory_p_status_b487dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_af1594_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='inventory_p_created_1d19a8_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'status'], name='inventory_p_product_d8c85b_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['quantity', 'minimum_quantity'], name='inventory_p_quantit_b34c20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='inventory_p_brand_28065a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='inventory_p_status_2ba142_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
    ]
