# Generated by Django 5.1.4 on 2025-11-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='Customer invoice item for sale transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='invoice.invoiceitem'),
        ),
    ]
