# Generated by Django 5.1.4 on 2025-12-23 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='Customer invoice item for sale transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='invoice.invoiceitem'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', False)), fields=('product', 'size', 'color'), name='unique_product_size_color'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('size__isnull', False)), fields=('product', 'size'), name='unique_product_size_null_color'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', True)), fields=('product', 'color'), name='unique_product_color_null_size'),
        ),
        migrations.AddField(
            model_name='favoritevariant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritevariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_variants', to='inventory.productvariant'),
        ),
        migrations.AddIndex(
            model_name='favoritevariant',
            index=models.Index(fields=['user'], name='inventory_f_user_id_e0ab07_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritevariant',
            index=models.Index(fields=['variant'], name='inventory_f_variant_639f77_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritevariant',
            index=models.Index(fields=['created_at'], name='inventory_f_created_958a4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritevariant',
            unique_together={('user', 'variant')},
        ),
    ]
