# Generated by Django 5.1.4 on 2025-12-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_favoritevariant_inventorylog_invoice_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_mappings', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
