# Generated by Django 5.1.4 on 2026-01-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_barcodemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='transaction_type',
            field=models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('RETURN', 'Customer Return'), ('CANCEL', 'Invoice Cancelled'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Mark as Damaged'), ('INITIAL', 'Initial Stock')], max_length=20),
        ),
    ]
