# Generated by Django 5.1.4 on 2026-03-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_dashboard', 'View Dashboard'), ('export_reports', 'Export Reports'), ('view_supplier_details', 'View Supplier Details'), ('view_low_stock_details', 'View Low Stock Details')]},
        ),
    ]
