# Generated by Django 5.1.4 on 2026-03-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Original uploaded file (kept at full quality).', upload_to='variant_media/%Y/%m/originals/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated optimised thumbnail for gallery view.', upload_to='variant_media/%Y/%m/thumbnails/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=5)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility.', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Is this the main media for the variant?')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Original file size in bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
