# Generated by Django 5.1.4 on 2026-03-16 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_variantmedia_delete_productimage'),
        ('invoice', '0003_alter_invoice_options'),
        ('supplier', '0003_supplierinvoice_supplier_su_is_dele_7bb5f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['supplier_invoice', 'transaction_type', 'quantity_change'], name='inventory_i_supplie_6b5f77_idx'),
        ),
    ]
