# Generated by Django 5.1.4 on 2026-03-18 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorylog_inventory_i_supplie_6b5f77_idx'),
        ('invoice', '0004_returninvoice_invoice_ret_status_b37f0f_idx'),
        ('supplier', '0003_supplierinvoice_supplier_su_is_dele_7bb5f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_type', 'variant', 'remaining_quantity'], name='inventory_i_transac_ff611e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant', 'transaction_type', 'timestamp'], name='inventory_i_variant_30cf8c_idx'),
        ),
    ]
