# Generated by Django 5.2 on 2026-05-31 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorylog_inventory_i_transac_ff611e_idx_and_more'),
        ('invoice', '0004_returninvoice_invoice_ret_status_b37f0f_idx'),
        ('supplier', '0003_supplierinvoice_supplier_su_is_dele_7bb5f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['invoice_item'], name='inventory_i_invoice_ca5f05_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['source_inventory_log'], name='inventory_i_source__724bb9_idx'),
        ),
    ]
