# Generated by Django 5.2 on 2026-06-25 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorylog_inventory_i_invoice_ca5f05_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_deleted', 'status'], name='inventory_p_is_dele_7bfff5_idx'),
        ),
    ]
