# Generated by Django 5.2 on 2026-07-29 22:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _get_supplier_info(InventoryLog, variant):
    """Helper to find supplier/invoice from DAMAGE or any log for a variant."""
    supplier_invoice = None
    supplier = None

    log = InventoryLog.objects.filter(
        variant=variant,
        transaction_type="DAMAGE",
        supplier_invoice__isnull=False,
    ).first()

    if not log:
        log = InventoryLog.objects.filter(
            variant=variant,
            supplier_invoice__isnull=False,
        ).first()

    if log and getattr(log, "supplier_invoice_id", None):
        supplier_invoice = log.supplier_invoice
        if supplier_invoice and getattr(supplier_invoice, "supplier_id", None):
            supplier = supplier_invoice.supplier

    return supplier, supplier_invoice


def backfill_damaged_records(apps, schema_editor):
    ProductVariant = apps.get_model("inventory", "ProductVariant")
    DamagedItemRecord = apps.get_model("inventory", "DamagedItemRecord")
    InventoryLog = apps.get_model("inventory", "InventoryLog")

    # --- Part 1: Variants with damaged_quantity > 0 but no DamagedItemRecord ---
    variants = ProductVariant.objects.filter(damaged_quantity__gt=0, is_deleted=False)
    for variant in variants:
        existing_qty = sum(
            (r.quantity for r in DamagedItemRecord.objects.filter(variant=variant, is_deleted=False)),
            Decimal("0"),
        )
        untracked = variant.damaged_quantity - existing_qty
        if untracked > 0:
            supplier, supplier_invoice = _get_supplier_info(InventoryLog, variant)
            DamagedItemRecord.objects.create(
                variant=variant,
                quantity=untracked,
                reason="GENERAL",
                notes="Backfilled from pre-existing damaged quantity in stock",
                status="PENDING",
                supplier=supplier,
                supplier_invoice=supplier_invoice,
            )

    # --- Part 2: Old DAMAGE logs where damaged_quantity is 0 (already sold stock) ---
    damage_variant_ids = (
        InventoryLog.objects.filter(transaction_type="DAMAGE", is_deleted=False)
        .values_list("variant_id", flat=True)
        .distinct()
    )

    for variant_id in damage_variant_ids:
        try:
            variant = ProductVariant.objects.get(id=variant_id, is_deleted=False)
        except ProductVariant.DoesNotExist:
            continue

        # Total damage from logs (quantity_change is negative, e.g. -5)
        total_logged = abs(
            sum(
                (
                    log.quantity_change
                    for log in InventoryLog.objects.filter(
                        variant=variant, transaction_type="DAMAGE", is_deleted=False
                    )
                ),
                Decimal("0"),
            )
        )

        if total_logged <= 0:
            continue

        # Already-recorded DamagedItemRecord qty (including Part 1 above)
        existing_qty = sum(
            (r.quantity for r in DamagedItemRecord.objects.filter(variant=variant, is_deleted=False)),
            Decimal("0"),
        )

        gap = total_logged - existing_qty
        if gap <= 0:
            continue

        supplier, supplier_invoice = _get_supplier_info(InventoryLog, variant)

        DamagedItemRecord.objects.create(
            variant=variant,
            quantity=gap,
            reason="GENERAL",
            notes="Backfilled from old DAMAGE inventory logs (sold stock)",
            status="PENDING",
            supplier=supplier,
            supplier_invoice=supplier_invoice,
        )

        # Update damaged_quantity on the variant to reflect the gap
        variant.damaged_quantity = (variant.damaged_quantity or Decimal("0")) + gap
        variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fix_cascade_to_protect'),
        ('supplier', '0006_add_status_and_name_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('GENERAL', 'General'), ('EXPIRED', 'Expired'), ('BROKEN', 'Broken / Unusable'), ('TRANSIT', 'Transit Damage'), ('WATER', 'Water Damage'), ('MANUFACTURING', 'Manufacturing Defect'), ('OTHER', 'Other')], default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Resolution'), ('RETURNED', 'Returned to Supplier'), ('WRITTEN_OFF', 'Written Off (Loss)'), ('REPAIRED', 'Repaired & Restored')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Credit received from supplier for returned items', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_resolved', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier from whom the damaged goods were purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_records', to='supplier.supplier')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_records', to='supplier.supplierinvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_records', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_d_status_4dfc46_idx'), models.Index(fields=['variant'], name='inventory_d_variant_74a12d_idx'), models.Index(fields=['supplier'], name='inventory_d_supplie_39fcd1_idx'), models.Index(fields=['created_at'], name='inventory_d_created_215a33_idx')],
            },
        ),
        migrations.RunPython(backfill_damaged_records, reverse_code=migrations.RunPython.noop),
    ]
