# Generated by Django 5.2 on 2026-08-06 19:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_damageditemrecord'),
        ('supplier', '0006_add_status_and_name_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads_created', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='supplier.supplierinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed')], db_index=True, default='DRAFT', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bulkupload')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.category')),
                ('cloth_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.clothtype')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.color')),
                ('hsn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.gsthsncode')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.size')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.uom')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_items', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['bulk_upload', 'sort_order'], name='inventory_b_bulk_up_a395f6_idx'), models.Index(fields=['status'], name='inventory_b_status_1fd711_idx'), models.Index(fields=['variant'], name='inventory_b_variant_992ad8_idx'), models.Index(fields=['product'], name='inventory_b_product_314d0b_idx')],
            },
        ),
    ]
