# Generated by Django 5.2 on 2026-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_bulkupload_bulkuploaditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_dashboard', 'View Dashboard'), ('export_reports', 'Export Reports'), ('view_supplier_details', 'View Supplier Details'), ('view_low_stock_details', 'View Low Stock Details'), ('view_supplier_invoice', 'View Supplier Invoice'), ('view_supplier_invoice_details', 'View Supplier Invoice Details')]},
        ),
    ]
