# Generated by Django 5.1.4 on 2026-03-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('view_dashboard', 'view dashboard'), ('download_report', 'download report')]},
        ),
    ]
