# Generated by Django 5.1.4 on 2026-03-16 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['is_deleted'], name='supplier_su_is_dele_7bb5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_date'], name='supplier_su_invoice_47a68d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['is_deleted', 'invoice_date'], name='supplier_su_is_dele_46f822_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['total_amount'], name='supplier_su_total_a_413794_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_number'], name='supplier_su_invoice_7b7cfd_idx'),
        ),
    ]
