# Generated by Django 5.2 on 2026-06-25 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierinvoice_supplier_su_is_dele_7bb5f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['is_deleted'], name='supplier_su_is_dele_351b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'is_deleted'], name='supplier_su_supplie_64a4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['payment_date'], name='supplier_su_payment_4d4287_idx'),
        ),
    ]
