# Generated by Django 5.2 on 2026-06-29 12:58

import django.db.models.deletion
import supplier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplierpayment_supplier_su_is_dele_351b1e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='supplier.supplierpayment'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_file',
            field=models.FileField(upload_to=supplier.models._media_upload_path, validators=[supplier.models.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='supplier.supplierinvoice'),
        ),
    ]
