# Generated by Django 5.2 on 2026-07-28 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_add_mediafile_payment_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_su_name_3342d4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_deleted'], name='supplier_su_is_dele_70301e_idx'),
        ),
    ]
