# Generated by Django 5.1.4 on 2025-12-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='Default Barcode', max_length=100)),
                ('barcode_type', models.CharField(choices=[('CODE128', 'Code 128'), ('EAN13', 'EAN-13'), ('QR', 'QR Code')], default='CODE128', max_length=10)),
                ('label_size', models.CharField(choices=[('25x12', '25mm x 12mm'), ('38x25', '38mm x 25mm'), ('50x25', '50mm x 25mm'), ('CUSTOM', 'Custom Size')], default='38x25', max_length=10)),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('ROLL', 'Label Roll')], default='A4', max_length=10)),
                ('show_heading', models.BooleanField(default=True, help_text='Show heading on barcode print page')),
                ('heading_text', models.CharField(blank=True, help_text="Custom heading to display on the barcode print page (e.g., 'SRI SAI GARMENTS' or 'Product Labels')", max_length=150, null=True)),
                ('custom_label_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_label_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('labels_per_row', models.PositiveIntegerField(default=2)),
                ('show_product_name', models.BooleanField(default=True)),
                ('show_product_code', models.BooleanField(default=True)),
                ('show_mrp', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_shop_logo', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_configs', to='setting.shopdetails')),
            ],
            options={
                'verbose_name': 'Barcode Configuration',
                'verbose_name_plural': 'Barcode Configurations',
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('shop', 'is_default'), name='unique_default_barcode_per_shop')],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(help_text="Name/Label for this payment method (e.g., 'Main Counter UPI', 'Paytm QR')", max_length=255)),
                ('payment_type', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Account'), ('QR', 'QR Code'), ('CARD', 'Card Payment'), ('WALLET', 'Wallet'), ('OTHER', 'Other')], default='UPI', help_text='Type of payment method', max_length=10)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for payments (e.g., shopname@paytm)', max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, help_text='Name of account holder', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code', max_length=11, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Bank branch name', max_length=255, null=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='Upload QR code image', null=True, upload_to='payment_qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, help_text='URL to generate QR code dynamically', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this payment method', null=True)),
                ('counter_name', models.CharField(blank=True, help_text="Counter/Location name (e.g., 'Counter 1', 'Online Store')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default payment method on invoices')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this payment method (lower number = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details_created', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(help_text='Shop this payment method belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='setting.shopdetails')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
                'ordering': ['display_order', '-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('shop', 'is_default'), name='unique_default_payment_per_shop')],
            },
        ),
    ]
