# Generated by Django 5.2 on 2026-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_barcodeconfiguration_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='is_direct_print_enabled',
            field=models.BooleanField(default=False, help_text='Enable direct printing to network printer'),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='printer_ip',
            field=models.CharField(blank=True, help_text='IP Address of the network printer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='printer_port',
            field=models.PositiveIntegerField(default=9100, help_text='Port of the network printer (default 9100)'),
        ),
    ]
