# Generated by Django 5.2 on 2026-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_shopdetails_is_direct_print_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='is_direct_print_enabled',
            field=models.BooleanField(default=False, help_text='Enable direct network thermal printing via socket'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='printer_ip',
            field=models.CharField(blank=True, help_text='Printer IP Address (e.g. 192.168.1.192)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='printer_port',
            field=models.IntegerField(blank=True, default=9100, help_text='Printer Port (default: 9100)', null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('58mm', '58mm Roll (2-inch)'), ('80mm', '80mm Roll (3-inch)'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='80mm', max_length=10),
        ),
    ]
