# Generated by Django 5.1.4 on 2025-12-24 16:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Advance payment received from customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
