# Generated by Django 5.1.4 on 2026-02-15 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('view_name', models.CharField(help_text='Name of the view/function', max_length=255)),
                ('user_role', models.CharField(help_text='Role of the user at time of attempt', max_length=20)),
                ('required_roles', models.CharField(help_text='Roles that were required', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who attempted unauthorized access', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unauthorized Access Attempt',
                'verbose_name_plural': 'Unauthorized Access Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
