# Generated by Django 5.1.4 on 2026-03-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_unauthorizedaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='unauthorizedaccess',
            name='user_role',
        ),
    ]
