# Generated by Django 5.2 on 2026-06-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_loginevent_unauthorizedaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view user dashboard')]},
        ),
    ]
