# Generated by Django 5.1.4 on 2025-11-20 12:58

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import invoice.mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Audit session title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the audit session')),
                ('audit_type', models.CharField(choices=[('CONVERSION', 'Invoice Conversion'), ('RENUMBER', 'Invoice Renumbering')], default='CONVERSION', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of audit period')),
                ('end_date', models.DateField(help_text='End date of audit period')),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_table_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('cart_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('original_invoice_no', models.CharField(blank=True, help_text='Original invoice number before conversion', max_length=50, null=True)),
                ('invoice_type', models.CharField(choices=[('GST', 'Gst'), ('CASH', 'Cash')], default='GST', max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total invoice amount before discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount given to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount received in advance (only for credit invoices)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI'), ('ONLINE_PAYMENT', 'Online Payment'), ('OTHER', 'Other')], default='CASH', max_length=25)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount paid against this invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST/SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_sold_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(invoice.mixins.InvoiceFinancialMixin, invoice.mixins.InvoiceValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('new_invoice_no', models.CharField(max_length=50)),
                ('reason', models.CharField(default='Invoice conversion', max_length=200)),
                ('change_type', models.CharField(choices=[('CONVERSION', 'Type Conversion'), ('RENUMBER', 'Number Change'), ('MODIFICATION', 'General Modification')], default='CONVERSION', max_length=20)),
                ('old_invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('new_invoice_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_audits', to='invoice.audittable')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_audit_changes', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoice.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Maximum Retail Price / Actual Price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual selling price per unit (after discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Cost price per unit (for profit calculation)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cess rate', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='GST percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.gsthsncode')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoice.invoice')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(invoice.mixins.InvoiceItemFinancialMixin, invoice.mixins.InvoiceItemValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('GST', 'Gst'), ('CASH', 'Cash')], default='GST', max_length=20)),
                ('financial_year', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_type', 'financial_year'], name='invoice_inv_invoice_3c3d82_idx')],
                'unique_together': {('invoice_type', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocation_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoice.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='customer.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, help_text='Auto-generated return invoice number', max_length=50, null=True, unique=True)),
                ('sequence_no', models.PositiveIntegerField(blank=True, null=True)),
                ('refund_type', models.CharField(choices=[('STORE_CREDIT', 'Store Credit'), ('CASH_REFUND', 'Cash Refund'), ('VOUCHER', 'Voucher'), ('EXCHANGE', 'Exchange'), ('OTHER', 'Other')], default='CASH_REFUND', help_text='Type of refund to be processed', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the return', max_length=20)),
                ('reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('STORE_POLICY', 'Store Policy'), ('DEFECTIVE_PRODUCT', 'Defective Product'), ('WRONG_PRODUCT', 'Wrong Product'), ('WRONG_SIZE', 'Wrong Size'), ('DAMAGED_IN_TRANSIT', 'Damaged in Transit'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], default='CUSTOMER_REQUEST', help_text='Reason for the return', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total return amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual amount to be refunded', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fee charged for restocking', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when return was initiated')),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date when return was approved', null=True)),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date when return was processed', null=True)),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the return', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='customer.customer')),
                ('invoice', models.ForeignKey(help_text='Original invoice being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='invoice.invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_modified_by', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_processed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity being returned', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_original', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Original quantity from invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Unit price at time of return', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount for this item', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('condition', models.CharField(choices=[('NEW', 'New/Unused'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective')], default='NEW', help_text='Condition of returned item', max_length=20)),
                ('return_reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item'), ('WRONG_SIZE', 'Wrong Size'), ('DAMAGED', 'Damaged in Transit'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], default='CUSTOMER_REQUEST', help_text='Reason for returning this specific item', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about this return item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_invoice_item', models.ForeignKey(blank=True, help_text='Original invoice item being returned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='invoice.invoiceitem')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_invoice_items', to='inventory.productvariant')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoice_items', to='invoice.returninvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['start_date', 'end_date'], name='invoice_aud_start_d_cc732d_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['created_at'], name='invoice_aud_created_9648aa_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['created_by'], name='invoice_aud_created_7b541b_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['audit_type'], name='invoice_aud_audit_t_69a244_idx'),
        ),
        migrations.AddIndex(
            model_name='audittable',
            index=models.Index(fields=['status'], name='invoice_aud_status_58ef11_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'payment_status'], name='invoice_inv_custome_fa39bf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_inv_invoice_54f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='invoice_inv_payment_b380c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoice_inv_invoice_aeba30_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_inv_invoice_a9b80b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['financial_year'], name='invoice_inv_financi_1ba394_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_type', 'financial_year'], name='invoice_inv_payment_c44247_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_inv_due_dat_b8a0e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_type', 'CASH'), ('advance_amount__lte', django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('discount_amount'))), _connector='OR')), name='advance_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_type', 'CASH'), ('paid_amount__lte', django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('discount_amount')))), models.Q(('paid_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('discount_amount')), '-', models.F('advance_amount'))), ('payment_type', 'CREDIT')), _connector='OR'), name='paid_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_type', 'CASH'), ('due_date__isnull', True), ('due_date__gte', models.F('invoice_date')), _connector='OR')), name='due_date_check'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_type', 'financial_year', 'sequence_no'), name='unique_invoice_sequence'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['invoice', 'created_at'], name='invoice_inv_invoice_e1788c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['created_at'], name='invoice_inv_created_1ec873_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['change_type'], name='invoice_inv_change__4f8fec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product_variant'], name='invoice_inv_invoice_f48b71_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product_variant'], name='invoice_inv_product_58ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_inv_invoice_a010ee_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['customer', 'status'], name='invoice_ret_custome_91a396_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['return_date'], name='invoice_ret_return__cd86fd_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['status'], name='invoice_ret_status_fa8bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['refund_type'], name='invoice_ret_refund__70e8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['financial_year'], name='invoice_ret_financi_c80900_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['invoice'], name='invoice_ret_invoice_d2c814_idx'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__lte', models.F('total_amount'))), name='refund_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), ('processed_date__isnull', True), _connector='OR')), name='processed_date_check'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('invoice',), name='unique_pending_return_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['return_invoice', 'product_variant'], name='invoice_ret_return__d3cb71_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['product_variant'], name='invoice_ret_product_64f781_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['condition'], name='invoice_ret_conditi_535b76_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['return_reason'], name='invoice_ret_return__72a8e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='returninvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__lte', models.F('quantity_original'))), name='return_quantity_check'),
        ),
    ]
