# Generated by Django 5.1.4 on 2026-01-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this invoice has been cancelled'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=25),
        ),
        migrations.CreateModel(
            name='InvoiceCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, help_text='When the cancellation occurred')),
                ('reason', models.TextField(help_text='Reason for cancellation')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original invoice amount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount amount at cancellation', max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, help_text='Advance amount at cancellation', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount paid at cancellation', max_digits=12)),
                ('payment_type', models.CharField(help_text='Payment type (CASH/CREDIT)', max_length=20)),
                ('cancelled_by', models.ForeignKey(help_text='User who cancelled the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_cancellations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(help_text='The cancelled invoice', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_record', to='invoice.invoice')),
            ],
            options={
                'ordering': ['-cancelled_at'],
                'indexes': [models.Index(fields=['cancelled_by'], name='invoice_inv_cancell_6cbbfc_idx'), models.Index(fields=['cancelled_at'], name='invoice_inv_cancell_4d3338_idx'), models.Index(fields=['payment_type'], name='invoice_inv_payment_9dd308_idx')],
            },
        ),
    ]
