# Generated by Django 5.1.4 on 2026-03-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_cancellation_reason_invoice_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'View Dashboard'), ('view_audit_details', 'View Audit Details'), ('export_audit_details', 'Export Audit Details')]},
        ),
    ]
