# Generated by Django 5.1.4 on 2026-03-18 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_customer_referred_by_idx_and_more'),
        ('invoice', '0003_alter_invoice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['status', 'customer', 'created_at'], name='invoice_ret_status_b37f0f_idx'),
        ),
    ]
