# Generated by Django 5.2 on 2026-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorylog_inventory_i_invoice_ca5f05_idx_and_more'),
        ('invoice', '0004_returninvoice_invoice_ret_status_b37f0f_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='returninvoiceitem',
            index=models.Index(fields=['original_invoice_item'], name='invoice_ret_origina_2e99c2_idx'),
        ),
    ]
