# Generated by Django 5.2 on 2026-06-25 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_customer_cu_is_dele_531b71_idx'),
        ('invoice', '0005_returninvoiceitem_invoice_ret_origina_2e99c2_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_cancelled', 'payment_type', 'invoice_date'], name='invoice_inv_is_canc_ffb062_idx'),
        ),
    ]
