# Generated by Django 5.2 on 2026-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_invoice_inv_is_canc_ffb062_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=25),
        ),
    ]
